### ISSUE TITLE
Full-screen Accordion Widget.

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#16]

**Comment by jig08** [comment]
Fullscreen `accordion`

![screenshot from 2015-08-06 00 56 01](https://cloud.githubusercontent.com/assets/9291400/9095896/822357e0-3bd7-11e5-8187-383f64344631.png)

**Comment by jigyasa-grover** [comment]
Full-Screen `accordion`

**HELP:**  `dialog #openFullscreen` did the trick.

![screenshot from 2015-08-06 01 09 03](https://cloud.githubusercontent.com/assets/9291400/9095954/e2787d50-3bd7-11e5-9e4a-3f28f739ec5a.png)
