### ISSUE TITLE
BrowseFiles window error !

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#26]
_Check code_ ; The entire screen has turned _black_.

**Comment by jigyasa-grover** [comment]
On each run, the `box` _ImageMorph_ keeps shifting downwards :cry: 

![screenshot from 2015-08-14 23 30 58](https://cloud.githubusercontent.com/assets/9291400/9282114/c2b6ca50-42e7-11e5-98d5-9f0596a884a4.png)

![screenshot from 2015-08-15 00 30 51](https://cloud.githubusercontent.com/assets/9291400/9282118/c68f2d16-42e7-11e5-9587-f7a58813b946.png)

**Comment by jigyasa-grover** [comment]
# Steps to reproduce:
1. Open a fresh image
2. Load Configuration : `World` > `Tools` > `Configuration Browser` > `sQuick_new`
3. Do It `IndexInterface open` in playground.
4. Click on `Browse Files` button.

On each run, the `box` _ImageMorph_ keeps shifting downwards :cry:

**Comment by jigyasa-grover** [comment]
@seandenigris @theseion
Any pointers pls ?

**Comment by theseion** [comment]
the problem seems to be that your list of files get longer every time you open the dialog. that seems to influence the position.
so there are two problems:
1. don’t add entries that are already in the list
2. the length of the file list shouldn’t influene the position of the other morphs

**Comment by jigyasa-grover** [comment]
@theseion Thank You :)
Will just work on it ...

**Comment by jigyasa-grover** [comment]
- Did not clear `Chapter` and `MyMenuItem` instances.
- Checked for the existence of document already present in `Chapter` instance (refer `Chapter entries contains: ...`) before adding it up in `browse` menu.

**Comment by jigyasa-grover** [comment]
@theseion 
Many thanks for your guidance :smiley:
