### ISSUE TITLE
Displaying the search results.

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#4]

**Comment by jigyasa-grover** [comment]
Search Results displayed.
NEXT: Make them clickable

**Comment by jigyasa-grover** [comment]
Search Results printed.

![02](https://cloud.githubusercontent.com/assets/9291400/8472977/567d8216-20c3-11e5-9a21-d8804e44c2c5.png)

NEXT: Make accordion widget, for a better UI.

**Comment by jigyasa-grover** [comment]
Accordion Widget made with the help of Expander Morphs.
ISSUE: Text being displayed beyond the label extent.
NEXT: Put up a PluggableTextMorph, maybe.

![screenshot from 2015-07-09 15 34 29](https://cloud.githubusercontent.com/assets/9291400/8592832/07713cb6-2650-11e5-8f38-a08463fe2f5c.png)

**Comment by seandenigris** [comment]
Great issue update!

**Comment by jigyasa-grover** [comment]
Text displayed.
NEXT: Scroll inclusion.

![screenshot from 2015-07-10 15 28 17](https://cloud.githubusercontent.com/assets/9291400/8616369/5640737a-2718-11e5-8331-39b01f4bd4da.png)

**Comment by jigyasa-grover** [comment]
Replacement of #newText: by #newTextEditorFor: to make the content of search results scroll-able.
Commit : https://github.com/jig08/sQuick_new/commit/8be246aedf8bded2a356edf87b1ee1d069d1c4e7

**Comment by jigyasa-grover** [comment]
Position & Extent of 'dialog' worked upon
Commit: https://github.com/jig08/sQuick_new/commit/1a4f695696ccf8732ed13cdef21bf3e708df71d1

**Comment by jigyasa-grover** [comment]
# NEXT

To prevent extension, addition of `Scroll Pane` in _accordion_ display list.

**Comment by jigyasa-grover** [comment]
## NEXT

To prevent extension, addition of `Scroll Pane` in accordion display list.

**\* New Issue #22 ***
