### ISSUE TITLE
CI build red signal 

### ISSUE THREAD

**Issue by jigyasa-grover** [jig08/sQuick_new#8]
Link: https://ci.inria.fr/pharo-contribution/job/sQuick/

**Comment by jigyasa-grover** [comment]
Removing text files to check for build error on CI
Commit: https://github.com/jig08/sQuick_new/commit/ac7b978dddf64d172b70039e2aedff78aefb9c1b

**Comment by jigyasa-grover** [comment]
Remove '?' from file name
Commit: https://github.com/jig08/sQuick_new/commit/86983b15255104f1b2e308729efef017c1195986

**Comment by jigyasa-grover** [comment]
Imrovised sQuick_new configuration (https://ci.inria.fr/pharo-contribution/job/sQuick_new/configure)
No error so far, still build fail.

## Console Output:

Started by user grover.jigyasa1@gmail.com
Building remotely on pharo-contribution-raspberrypi-linux (raspberry-cross) in workspace /builds/workspace/sQuick_new

Deleting project workspace... done

Cloning the remote Git repository
Cloning repository https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Checking out Revision c10915fea3d5f0c211e684b9d82b3f009d92cbdf (origin/master)
Triggering 40,stable,vm
Triggering 40,development,vm
40,stable,vm completed with result FAILURE
40,development,vm completed with result FAILURE
Finished: FAILURE

**Comment by jigyasa-grover** [comment]
Changed Execute Shell Command:
REPO=http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/$JOB_NAME

## Console Output:

Started by upstream project "[8mha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyuEgYB/az8JP3iwNLM5Oz4vNRyfQBNvDy8xQAAAA==[0msQuick_new" build number [8mha:AAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAwmoBn6WflJ+sWBpZnJ2fF5qeX6RoYAlhSAt8cAAAA=[0m21
originally caused by:
 Started by user grover.jigyasa1@gmail.com
Building remotely on pharo-contribution-linux64-3.ci.inria.fr in workspace /builds/workspace/sQuick_new/PHARO/40/VERSION/stable/VM/vm

Deleting project workspace... Cloning the remote Git repository
Cloning repository https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Checking out Revision 962a498589f5cf050a8a9c8999c2b8b5eef28695 (origin/master)
Deleting old artifacts from #19
[vm] $ /bin/sh -xe /tmp/hudson6368912702163584529.sh
- dirname sQuick_new/PHARO=40,VERSION=stable,VM=vm
- export JOB_NAME=sQuick_new
- wget --quiet -O - get.pharo.org/40+vm
- bash
  Downloading the latest 40 Image:
  http://files.pharo.org/get-files/40/pharo.zip
  Pharo.image
  Downloading the latest pharoVM:
  http://files.pharo.org/get-files/40/pharo-linux-stable.zip
  pharo-vm/pharo
  Downloading PharoV40.sources:
  http://files.pharo.org/get-files/40/sources.zip
  Creating starter scripts pharo and pharo-ui
- ./pharo Pharo.image save sQuick_new --delete-old
- ./pharo sQuick_new.image --version
- REPO=http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new
- ./pharo sQuick_new.image config http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new ConfigurationOfsQuick_new --install=stable
  'Installing ConfigurationOfsQuick_new stable'

Loading 1.0 of ConfigurationOfsQuick_new...
Fetched -> BaselineOfsQuick_new-jigyasagrover.3 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Loaded -> BaselineOfsQuick_new-jigyasagrover.3 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Project: sQuick_new baseline
Fetched -> sQuick_new-jigyasa.56 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Loaded -> sQuick_new-jigyasa.56 --- github://jig08/sQuick_new:master --- cache
...finished 1.0+ ./pharo sQuick_new.image test --junit-xml-output sQuick_new.*
'Running tests in 1 Packages'
- zip -r sQuick_new.zip sQuick_new.image sQuick_new.changes
  adding: sQuick_new.image (deflated 58%)
  adding: sQuick_new.changes (deflated 90%)
- rm -rf sQuick_new.image sQuick_new.changes
  Archiving artifacts
  Recording test results
  Build step 'Publish JUnit test result report' changed build result to UNSTABLE
  regression reporter starts now...
  regression reporter ends.

Deleting project workspace... 
done

Finished: UNSTABLE

**Comment by jigyasa-grover** [comment]
Automated Build results:
- Version = stable  > UNSTABLE
- Version = development > FAILURE

## Console Output (40, development, VM) 

Started by upstream project "[8mha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyuEgYB/az8JP3iwNLM5Oz4vNRyfQBNvDy8xQAAAA==[0msQuick_new" build number [8mha:AAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAwmoBn6WflJ+sWBpZnJ2fF5qeX6RkYALEWJLscAAAA=[0m22
originally caused by:
 Started by timer
Building remotely on pharo-contribution-linux64-3.ci.inria.fr in workspace /builds/workspace/sQuick_new/PHARO/40/VERSION/development/VM/vm

Deleting project workspace... Cloning the remote Git repository
Cloning repository https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Checking out Revision 962a498589f5cf050a8a9c8999c2b8b5eef28695 (origin/master)
Deleting old artifacts from #20
[vm] $ /bin/sh -xe /tmp/hudson4644252410862402859.sh
- dirname sQuick_new/PHARO=40,VERSION=development,VM=vm
- export JOB_NAME=sQuick_new
- bash
- wget --quiet -O - get.pharo.org/40+vm
  Downloading the latest 40 Image:
  http://files.pharo.org/get-files/40/pharo.zip
  Pharo.image
  Downloading the latest pharoVM:
  http://files.pharo.org/get-files/40/pharo-linux-stable.zip
  pharo-vm/pharo
  Downloading PharoV40.sources:
  http://files.pharo.org/get-files/40/sources.zip
  Creating starter scripts pharo and pharo-ui
- ./pharo Pharo.image save sQuick_new --delete-old
- ./pharo sQuick_new.image --version
- REPO=http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new
- ./pharo sQuick_new.image config http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new ConfigurationOfsQuick_new --install=development
  'Installing ConfigurationOfsQuick_new development'

==== Startup Error: The symbolic version '0.1-baseline' is not defined in ConfigurationOfsQuick_new for the current platform. Possible symbolic version values include: #(#bleedingEdge #development #stable)

[ (MetacelloSymbolicVersionDoesNotExistError project: self project versionString: symbolicVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloSymbolicVersionDoesNotExistError proje...etc...
[ ^ aBlock value ] in [ 
(MetacelloVersionDefinitionError project: self project versionString: aVersionString)
    exception: (self errorMap at: aVersionString ifAbsent: [ ^ aBlock value ]);
    signal ] in MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent: in Block: [ ^ aBlock value ]
Dictionary>>at:ifAbsent:
[ 
(MetacelloVersionDefinitionError project: self project versionString: aVersionString)
    exception: (self errorMap at: aVersionString ifAbsent: [ ^ aBlock value ]);
    signal ] in MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent: in Block: [ ...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ :error | 
aVersionName = 'last'
    ifTrue: [ 
        "manual fallback since there is no symbolic name for lastVersion"
        project lastVersion ]
    ifFalse: [ 
        "symbols and strings are not equal in Meteacello..."
        project version: aVersionName asSymbol ] ] in ConfigurationCommandLineHandler>>metacelloVersion: in Block: [ :error | ...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
MetacelloVersionDoesNotExistError(Exception)>>signal
[ (MetacelloVersionDoesNotExistError project: self project versionString: aVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloVersionDoesNotExistError project: self...etc...
[ ^ aBlock value ] in [ 
(MetacelloVersionDefinitionError project: self project versionString: aVersionString)
    exception: (self errorMap at: aVersionString ifAbsent: [ ^ aBlock value ]);
    signal ] in MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent: in Block: [ ^ aBlock value ]
Dictionary>>at:ifAbsent:
[ 
(MetacelloVersionDefinitionError project: self project versionString: aVersionString)
    exception: (self errorMap at: aVersionString ifAbsent: [ ^ aBlock value ]);
    signal ] in MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent: in Block: [ ...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>lookupVersion:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ project version: aVersionName ] in ConfigurationCommandLineHandler>>metacelloVersion: in Block: [ project version: aVersionName ]
BlockClosure>>on:do:
ConfigurationCommandLineHandler>>metacelloVersion:
ConfigurationCommandLineHandler>>installVersion:
ConfigurationCommandLineHandler>>installConfiguration
ConfigurationCommandLineHandler>>activate
ConfigurationCommandLineHandler class(CommandLineHandler class)>>activateWith:
[ aCommandLinehandler activateWith: commandLine ] in PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand: in Block: [ aCommandLinehandler activateWith: commandLine ]
BlockClosure>>on:do:
PharoCommandLineHandler(BasicCommandLineHandler)>>activateSubCommand:
PharoCommandLineHandler(BasicCommandLineHandler)>>handleSubcommand
Got startup errors: 
    The symbolic version '0.1-baseline' is not defined in ConfigurationOfsQuick_new for the current platform. Possible symbolic version values include: #(#bleedingEdge #development #stable)
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
regression reporter doesn't run because test doesn't run.

Deleting project workspace... 
done

Finished: FAILURE

**Comment by jigyasa-grover** [comment]
Changed baseline versions from 1.0 to 0.1 (Commit: https://github.com/jig08/ConfigurationOfsQuick_new/commit/69b248b09288cedb45d55d29562fd17dcd8f9e97 )

## Console Output:

Started by upstream project "[8mha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyuEgYB/az8JP3iwNLM5Oz4vNRyfQBNvDy8xQAAAA==[0msQuick_new" build number [8mha:AAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAwmoBn6WflJ+sWBpZnJ2fF5qeX6xoYA1yWbrscAAAA=[0m31
originally caused by:
 Started by user grover.jigyasa1@gmail.com
Building remotely on pharo-contribution-linux64-3.ci.inria.fr in workspace /builds/workspace/sQuick_new/PHARO/40/VERSION/development/VM/vm

Deleting project workspace... Cloning the remote Git repository
Cloning repository https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Checking out Revision ae446951a9f9352b00280df22b23f82a54eddbc6 (origin/master)
Deleting old artifacts from #29
[vm] $ /bin/sh -xe /tmp/hudson1148380658282228327.sh
- dirname sQuick_new/PHARO=40,VERSION=development,VM=vm
- export JOB_NAME=sQuick_new
- wget --quiet -O - get.pharo.org/40+vm
- bash
  Downloading the latest 40 Image:
  http://files.pharo.org/get-files/40/pharo.zip
  Pharo.image
  Downloading the latest pharoVM:
  http://files.pharo.org/get-files/40/pharo-linux-stable.zip
  pharo-vm/pharo
  Downloading PharoV40.sources:
  http://files.pharo.org/get-files/40/sources.zip
  Creating starter scripts pharo and pharo-ui
- ./pharo Pharo.image save sQuick_new --delete-old
- ./pharo sQuick_new.image --version
- REPO=http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new
- ./pharo sQuick_new.image config http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new ConfigurationOfsQuick_new --install=development
  'Installing ConfigurationOfsQuick_new development'

Loading 0.1-baseline of ConfigurationOfsQuick_new...
...RETRY->sQuick_new
...RETRY->sQuick_new
...FAILED->sQuick_new==== Startup Error: Could not resolve: sQuick_new [sQuick_new] in /builds/workspace/sQuick_new/PHARO/40/VERSION/development/VM/vm/package-cache
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>retryingResolvePackageSpecReferences:gofer:
linearLoadPackageSpec: packageSpec gofer: gofer
    MetacelloPlatform current
        do: [ 
            | references nearestReference cachedReference externalReference mcVersion loadedVersionInfos |
            "check to see if mcz file is already in cacheRepository"
            cachedReference := self resolvePackageSpec: packageSpec cachedGofer: self loaderPolicy cacheGofer.
            (cachedReference ~~ nil and: [ packageSpec getFile ~~ nil ])
                ifTrue: [ 
                    cachedReference name = packageSpec file
                        ifTrue: [ 
                            "exact match between packageSpec file and cache"
                            ^ self scheduleFetchFor: packageSpec cachedReference: cachedReference ] ].  "look up mcz file"
            references := self retryingResolvePackageSpecReferences: packageSpec gofer: gofer.
            nearestReference := references last asMetacelloCachingResolvedReference.    "If the mcz is already in the cacheRepository, no need to copy"
            (cachedReference ~~ nil and: [ cachedReference name = nearestReference name ])
                ifTrue: [ 
                    "latest reference in repository matches cachedReference ... "
                    ^ self scheduleFetchFor: packageSpec nearestReference: nearestReference ].  "If the mcz is already loaded into the image, no need to copy"
            (self ignoreImage not and: [ (loadedVersionInfos := self ancestorsFor: packageSpec) ~~ nil ])
                ifTrue: [ 
                    loadedVersionInfos
                        do: [ :info | 
                            info name = nearestReference name
                                ifTrue: [ ^ self ] ] ].
            externalReference := (references select: [ :ref | ref name = nearestReference name ]) first
                asMetacelloCachingResolvedReference.
            self repositoryMap at: externalReference name put: externalReference repository.
            (self
                resolveDependencies: externalReference
                nearest: nearestReference
                into: (OrderedCollection with: nearestReference))
                do: [ :reference | 
                    | pSpec l |
                    mcVersion := reference version.
                    (l := (GoferVersionReference name: reference name) resolveAllWith: self loaderPolicy cacheGofer) isEmpty
                        ifTrue: [ 
                            self cacheRepository storeVersion: mcVersion.
                            reference == nearestReference
                                ifTrue: [ pSpec := packageSpec ]
                                ifFalse: [ 
                                    pSpec := packageSpec project packageSpec.
                                    pSpec name: mcVersion package name ].
                            self loadData
                                addVersion: mcVersion
                                versionInfo: mcVersion info
                                resolvedReference: reference
                                packageSpec: pSpec ] ].
            self scheduleFetchFor: packageSpec externalReference: externalReference ]
        displaying: 'Fetching ' , packageSpec file in MetacelloFetchingMCSpecLoader>>linearLoadPackageSpec:gofer: in Block: linearLoadPackageSpec: packageSpec gofer: gofer...
MetacelloPharo30Platform(MetacelloPlatform)>>do:displaying:
MetacelloFetchingMCSpecLoader>>linearLoadPackageSpec:gofer:
MetacelloPackageSpec>>loadUsing:gofer:
[ :pkg | pkg loadUsing: self gofer: gofer ] in MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>linearLoadPackageSpecs:repositories: in Block: [ :pkg | pkg loadUsing: self gofer: gofer ]
OrderedCollection>>do:
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>linearLoadPackageSpecs:repositories:
[ super linearLoadPackageSpecs: packageSpecs repositories: repositories ] in MetacelloFetchingMCSpecLoader>>linearLoadPackageSpecs:repositories: in Block: [ super linearLoadPackageSpecs: packageSpecs repos...etc...
BlockClosure>>ensure:
MetacelloLoaderPolicy>>pushLoadDirective:during:
MetacelloLoaderPolicy>>pushLinearLoadDirectivesDuring:for:
MetacelloFetchingMCSpecLoader>>linearLoadPackageSpecs:repositories:
MetacelloFetchingMCSpecLoader(MetacelloCommonMCSpecLoader)>>load
MetacelloMCVersionSpecLoader>>load
MetacelloMCVersion>>executeLoadFromArray:
[ :dict | ^ self executeLoadFromArray: anArray ] in [ 
self versionSpec loader: newLoader.
MetacelloPlatform current
    useStackCacheDuring: [ :dict | ^ self executeLoadFromArray: anArray ]
    defaultDictionary: Dictionary new ] in [ 
[ 
self versionSpec loader: newLoader.
MetacelloPlatform current
    useStackCacheDuring: [ :dict | ^ self executeLoadFromArray: anArray ]
    defaultDictionary: Dictionary new ]
    ensure: [ self versionSpec loader: originalLoader ] ] in MetacelloMCVersion>>fetchRequiredFromArray: in Block: [ :dict | ^ self executeLoadFromArray: anArray ]
[ ^ aBlock value: dict ] in MetacelloPharo30Platform(MetacelloPlatform)>>useStackCacheDuring:defaultDictionary: in Block: [ ^ aBlock value: dict ]
BlockClosure>>on:do:
MetacelloPharo30Platform(MetacelloPlatform)>>useStackCacheDuring:defaultDictionary:
[ 
self versionSpec loader: newLoader.
MetacelloPlatform current
    useStackCacheDuring: [ :dict | ^ self executeLoadFromArray: anArray ]
    defaultDictionary: Dictionary new ] in [ 
[ 
self versionSpec loader: newLoader.
MetacelloPlatform current
    useStackCacheDuring: [ :dict | ^ self executeLoadFromArray: anArray ]
    defaultDictionary: Dictionary new ]
    ensure: [ self versionSpec loader: originalLoader ] ] in MetacelloMCVersion>>fetchRequiredFromArray: in Block: [ ...
BlockClosure>>ensure:
[ 
[ 
self versionSpec loader: newLoader.
MetacelloPlatform current
    useStackCacheDuring: [ :dict | ^ self executeLoadFromArray: anArray ]
    defaultDictionary: Dictionary new ]
    ensure: [ self versionSpec loader: originalLoader ] ] in MetacelloMCVersion>>fetchRequiredFromArray: in Block: [ ...
MetacelloPharo30Platform(MetacelloPlatform)>>do:displaying:
MetacelloMCVersion>>fetchRequiredFromArray:
[ 
| fetchLoader |
fetchLoader := self fetchRequiredFromArray: (self defaultPackageNamesToLoad: anArray).
MetacelloPlatform current do: [ fetchLoader doLoad ] displaying: 'Loading ' , displayString.
Transcript
    cr;
    show: '...finished ' , self versionNumber printString.
^ fetchLoader ] in MetacelloMCVersion>>doLoadRequiredFromArray: in Block: [ ...
BlockClosure>>ensure:
MetacelloMCVersion>>doLoadRequiredFromArray:
MetacelloMCVersion>>load
[ 
(self hasOption: 'group')
    ifTrue: [ metacelloVersion load: self groups ]
    ifFalse: [ metacelloVersion load ] ] in ConfigurationCommandLineHandler>>installVersion: in Block: [ ...
Got startup errors: 
    Could not resolve: sQuick_new [sQuick_new] in /builds/workspace/sQuick_new/PHARO/40/VERSION/development/VM/vm/package-cache
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
regression reporter doesn't run because test doesn't run.

Deleting project workspace... 
done

Finished: FAILURE

**Comment by jigyasa-grover** [comment]
Resolved failing test assertions. Replaced #assert: with #deny:
Commit: https://github.com/jig08/sQuick_new/commit/a923797b73f7dfa0c781afb9c91b2903c8e1a247

Automated Build results:
- Version = stable -> SUCCESS
- Version = development  -> FAILURE

## Console Output (Pharo 40,Version=stable,VM=vm)

Started by upstream project "[8mha:AAAAnB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyuEgYB/az8JP3iwNLM5Oz4vNRyfQBNvDy8xQAAAA==[0msQuick_new" build number [8mha:AAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAwmoBn6WflJ+sWBpZnJ2fF5qeX6xpYA5a1AoMcAAAA=[0m39
originally caused by:
 Started by user grover.jigyasa1@gmail.com
Building remotely on pharo-contribution-linux64-3.ci.inria.fr in workspace /builds/workspace/sQuick_new/PHARO/40/VERSION/stable/VM/vm

Deleting project workspace... Cloning the remote Git repository
Cloning repository https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Fetching upstream changes from https://github.com/jig08/sQuick_new
Checking out Revision a923797b73f7dfa0c781afb9c91b2903c8e1a247 (origin/master)
Deleting old artifacts from #37
[vm] $ /bin/sh -xe /tmp/hudson6073093246148812504.sh
- dirname sQuick_new/PHARO=40,VERSION=stable,VM=vm
- export JOB_NAME=sQuick_new
- bash
- wget --quiet -O - get.pharo.org/40+vm
  Downloading the latest 40 Image:
  http://files.pharo.org/get-files/40/pharo.zip
  Pharo.image
  Downloading the latest pharoVM:
  http://files.pharo.org/get-files/40/pharo-linux-stable.zip
  pharo-vm/pharo
  Downloading PharoV40.sources:
  http://files.pharo.org/get-files/40/sources.zip
  Creating starter scripts pharo and pharo-ui
- ./pharo Pharo.image save sQuick_new --delete-old
- ./pharo sQuick_new.image --version
- REPO=http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new
- ./pharo sQuick_new.image config http://smalltalkhub.com/mc/Pharo/MetaRepoForPharo40/main/sQuick_new ConfigurationOfsQuick_new --install=stable
  'Installing ConfigurationOfsQuick_new stable'

Loading 0.1 of ConfigurationOfsQuick_new...
Fetched -> BaselineOfsQuick_new-jigyasagrover.3 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Loaded -> BaselineOfsQuick_new-jigyasagrover.3 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Project: sQuick_new baseline
Fetched -> sQuick_new-jigyasa.60 --- github://jig08/sQuick_new:master --- github://jig08/sQuick_new:master
Loaded -> sQuick_new-jigyasa.60 --- github://jig08/sQuick_new:master --- cache
...finished 0.1+ ./pharo sQuick_new.image test --junit-xml-output sQuick_new.*
'Running tests in 1 Packages'
- zip -r sQuick_new.zip sQuick_new.image sQuick_new.changes
  adding: sQuick_new.image (deflated 58%)
  adding: sQuick_new.changes (deflated 90%)
- rm -rf sQuick_new.image sQuick_new.changes
  Archiving artifacts
  Recording test results
  regression reporter doesn't run because build is success.

Deleting project workspace... 
done

Finished: SUCCESS

**Comment by seandenigris** [comment]
Hooray! One down, one to go :)

**Comment by jigyasa-grover** [comment]
Yayy :smiley:

**Comment by seandenigris** [comment]
The problem seems to be that our tools (e.g. CI, Metacello) have yet been completely adapted for Git development. The Git world doesn't map well by default to Metacello's concepts of #stable and #development. There is, for example, no `baseline` equivalent to Pharo's `config` command line handler.
For this and other reasons, scripting the #development build cleanly requires an answer to [a question I asked on the Metacello list](http://forum.world.st/GitHub-Configs-tp4830432p4841140.html), so for now I hacked in an ugly case statement to get both builds green and move things along.

**Comment by jigyasa-grover** [comment]
Okay Sir :+1:
